- name: Build environment
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: DN instance create request
      local_action:
        module: rax_cdb
        credentials: ./repo
        region: LON
        name: "{{ dbinstancename }}"
        flavor: "{{ ramdbinstancename }}"
        volume: "{{ diskdbinstancename }}"
        wait: yes
        state: present
      register: cloinst
    - name: DB create request
      local_action:
        module: rax_cdb_database
        credentials: ./repo
        region: LON
        cdb_id: "{{ cloinst.cdb.id }}"
        name: "{{ appdbname }}"
        state: present
      register: rax_db_database
    - debug: msg={{ cloinst.cdb.hostname }}
    - name: Create user inside DB
      local_action:
        module: rax_cdb_user
        credentials: ./repo
        region: LON
        cdb_id: "{{ cloinst.cdb.id }}"
        db_username: "{{ userappdbname }}"
        db_password: "{{ passuserappdbname }}"
        databases: "{{ rax_db_database.database.name }}"
        state: present
      register: rax_db_user
    - name: DB create request
      local_action:
        module: rax_cdb_database
        credentials: ./repo
        region: LON
        cdb_id: "{{ cloinst.cdb.id }}"
        name: "{{ BEdbname }}"
        state: present
      register: rax_db_database_s
    - name: Create user inside DB
      local_action:
        module: rax_cdb_user
        credentials: ./repo
        region: LON
        cdb_id: "{{ cloinst.cdb.id }}"
        db_username: "{{ userBEdbname }}"
        db_password: "{{ passuserBEdbname }}"
        databases: "{{ rax_db_database_s.database.name }}"
        state: present
      register: rax_db_user
